nelmio_cors:
    defaults:
        allow_origin: ['https://arcadia35380-f680d3a74682.herokuapp.com','http://localhost:8000','http://localhost:3000/']  # Autorise toutes les origines
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': 
            allow_origin: ['https://arcadia35380-f680d3a74682.herokuapp.com','http://localhost:8000','http://localhost:3000/']  # Autorise toutes les origines pour les API
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
            expose_headers: ['Link']
            max_age: 3600
        '^/image/':
            allow_origin: ['https://arcadia35380-f680d3a74682.herokuapp.com','http://localhost:8000','http://localhost:3000/']  # Autorise toutes les origines pour les images
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
            expose_headers: ['Link']
            max_age: 3600