security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
    access_control:
        - { path: ^/api/service, roles: [ROLE_EMPLOYE, ROLE_ADMIN], methods: [PUT] }
        - { path: ^/api/service/post, roles: ROLE_ADMIN, methods: [POST] }
        - { path: ^/api/service, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/service, roles: [ROLE_EMPLOYE, ROLE_ADMIN], methods: [DELETE] }

        - { path: ^/api/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/horaire/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/horaire/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/avis/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/avis/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/avis/post, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/habitat/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/habitat, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/race/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/race/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/animal/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/animal, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/rapportveterinaire/post, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }