# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

    access_control:
        - { path: ^/api/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/service/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to this route
        - { path: ^/api/horaire/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to this route
        - { path: ^/api/avis/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to this route
        - { path: ^/api/habitat/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to this route
        - { path: ^/api/animal/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to this route

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
