index:
    path: /
    controller: App\Controller\DefaultController::index

# Other routes
horaire_list:
    path: /api/horaires/get
    controller: App\Controller\HoraireController::list

avis_get:
    path: /api/avis
    controller: App\Controller\AvisController::/
    methods: [GET]

api_service_get:
    path: /api/service/get
    controller: App\Controller\ServiceController::getService
    methods: [GET]