services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Correct the ApiTokenAuthenticator service definition
    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'

    # Configure le service Redis
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments: ['redis', 6379]  # Utiliser le nom du service Redis

    App\Service\RedisService:
        arguments:
            $redis: '@Redis'  # Assurez-vous que Redis est injecté correctement
