services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Correct the ApiTokenAuthenticator service definition
    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'

    # Configure le service Redis
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDISCLOUD_URL)%' # Pour production
                  - 0 # 0 est généralement utilisé pour le port par défaut
    
    App\Service\RedisService:
        arguments:
            $redis: '@Redis'  # Assurez-vous que Redis est injecté correctement  
