services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Correct the ApiTokenAuthenticator service definition
    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'

    # Configure le service Redis
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(resolve:REDISCLOUD_URL_HOST)%'  # Hôte de Redis extrait
                  - '%env(resolve:REDISCLOUD_URL_PORT)%'  # Port de Redis extrait
            - method: auth
              arguments:
                  - '%env(resolve:REDISCLOUD_URL_PASS)%'  # Mot de passe Redis