# config/services_prod.yaml

services:
    App\Service\RedisService:
        arguments:
            $redis: '@redis'

    Predis\Client:
        arguments:
            $parameters: '%env(REDIS_URL)%'
