services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'

    App\Factory\RedisFactory:
        arguments:
            $redisUrl: '%env(OPENREDIS_URL)%'  

    # Configure le service RedisService
    App\Service\RedisService:
        arguments:
            $redisUrl: '%env(OPENREDIS_URL)%'
            $logger: '@logger'  