services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Correct the ApiTokenAuthenticator service definition
    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'

    # Configure le service Redis
    App\Service\RedisService:
        arguments:
            $redisUrl: '%env(OPENREDIS_URL)%'  # Utiliser %env() pour s'assurer que c'est une variable d'environnement
